spring:
  application:
    name: enrollment-service

  datasource:
    url: jdbc:postgresql://localhost:5432/enrollment_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: 8083