server:
  port: 8085

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:5437/auth_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml