spring:
  application:
    name: notification-service

  datasource:
    url: jdbc:postgresql://localhost:5436/notification_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

server:
  port: 8084

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui



