services:

  user-postgres:
    image: postgres:16
    container_name: user-postgres
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - user-postgres-data:/var/lib/postgresql/data

  course-postgres:
    image: postgres:16
    container_name: course-postgres
    environment:
      POSTGRES_DB: course_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - course-postgres-data:/var/lib/postgresql/data

  enrollment-postgres:
    image: postgres:16
    container_name: enrollment-postgres
    environment:
      POSTGRES_DB: enrollment_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    volumes:
      - enrollment-postgres-data:/var/lib/postgresql/data

  notification-postgres:
    image: postgres:16
    container_name: notification-postgres
    environment:
      POSTGRES_DB: notification_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5436:5432"
    volumes:
      - notification-postgres-data:/var/lib/postgresql/data

volumes:
  user-postgres-data:
  course-postgres-data:
  enrollment-postgres-data:
  notification-postgres-data: