name: Training Center CI

on:                       #означает: при каком событии запускать workflow
  push:
    branches:
      - feature/cicd

permissions:
  contents: read
  packages: write

jobs:                         #список работ, которые должен выполнить наш CI.
  build:                      #имя job, которое придумали мы. Можно было назвать build-project, test и т. д.
    runs-on: ubuntu-latest    #Для выполнения build используем Linux-машину с Ubuntu на GitHub.

    steps:                    #последовательные шаги внутри одного job.
      - name: Checkout repository
        uses: actions/checkout@v5    #Выполнение следующих команд в терминале Ubuntu Runner.

      - name: Set up Java 21
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '21'

      - name: Check environment
        run: |
          java -version
          mvn -version
          pwd
          ls -la

      - name: Compile project
        run: ./mvnw clean compile

      - name: Run unit tests
        run: ./mvnw test

      - name: Package application
        run: ./mvnw package -DskipTests

      - name: Show generated JAR files
        run: find . -path "*/target/*.jar" -type f

      - name: Build user-service Docker image
        run: |
          docker build \
            -t ghcr.io/samatb/user-service:ci \
            -t ghcr.io/samatb/user-service:${{ github.sha }} \
            ./user-service

      - name: Show Docker images
        run: docker images

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push user-service Docker image
        run: |
          docker push ghcr.io/samatb/user-service:ci
          docker push ghcr.io/samatb/user-service:${{ github.sha }}